// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.0
// source: internal.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayDeliveryService_DeliverMessage_FullMethodName = "/livechat.internal.GatewayDeliveryService/DeliverMessage"
)

// GatewayDeliveryServiceClient is the client API for GatewayDeliveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayDeliveryServiceClient interface {
	DeliverMessage(ctx context.Context, in *DeliverMessageRequest, opts ...grpc.CallOption) (*DeliverMessageResponse, error)
}

type gatewayDeliveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayDeliveryServiceClient(cc grpc.ClientConnInterface) GatewayDeliveryServiceClient {
	return &gatewayDeliveryServiceClient{cc}
}

func (c *gatewayDeliveryServiceClient) DeliverMessage(ctx context.Context, in *DeliverMessageRequest, opts ...grpc.CallOption) (*DeliverMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliverMessageResponse)
	err := c.cc.Invoke(ctx, GatewayDeliveryService_DeliverMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayDeliveryServiceServer is the server API for GatewayDeliveryService service.
// All implementations must embed UnimplementedGatewayDeliveryServiceServer
// for forward compatibility.
type GatewayDeliveryServiceServer interface {
	DeliverMessage(context.Context, *DeliverMessageRequest) (*DeliverMessageResponse, error)
	mustEmbedUnimplementedGatewayDeliveryServiceServer()
}

// UnimplementedGatewayDeliveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayDeliveryServiceServer struct{}

func (UnimplementedGatewayDeliveryServiceServer) DeliverMessage(context.Context, *DeliverMessageRequest) (*DeliverMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeliverMessage not implemented")
}
func (UnimplementedGatewayDeliveryServiceServer) mustEmbedUnimplementedGatewayDeliveryServiceServer() {
}
func (UnimplementedGatewayDeliveryServiceServer) testEmbeddedByValue() {}

// UnsafeGatewayDeliveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayDeliveryServiceServer will
// result in compilation errors.
type UnsafeGatewayDeliveryServiceServer interface {
	mustEmbedUnimplementedGatewayDeliveryServiceServer()
}

func RegisterGatewayDeliveryServiceServer(s grpc.ServiceRegistrar, srv GatewayDeliveryServiceServer) {
	// If the following call pancis, it indicates UnimplementedGatewayDeliveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayDeliveryService_ServiceDesc, srv)
}

func _GatewayDeliveryService_DeliverMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayDeliveryServiceServer).DeliverMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayDeliveryService_DeliverMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayDeliveryServiceServer).DeliverMessage(ctx, req.(*DeliverMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayDeliveryService_ServiceDesc is the grpc.ServiceDesc for GatewayDeliveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayDeliveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "livechat.internal.GatewayDeliveryService",
	HandlerType: (*GatewayDeliveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeliverMessage",
			Handler:    _GatewayDeliveryService_DeliverMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal.proto",
}

const (
	MessageAckService_ProcessAck_FullMethodName = "/livechat.internal.MessageAckService/ProcessAck"
)

// MessageAckServiceClient is the client API for MessageAckService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageAckServiceClient interface {
	ProcessAck(ctx context.Context, in *ProcessAckRequest, opts ...grpc.CallOption) (*ProcessAckResponse, error)
}

type messageAckServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageAckServiceClient(cc grpc.ClientConnInterface) MessageAckServiceClient {
	return &messageAckServiceClient{cc}
}

func (c *messageAckServiceClient) ProcessAck(ctx context.Context, in *ProcessAckRequest, opts ...grpc.CallOption) (*ProcessAckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessAckResponse)
	err := c.cc.Invoke(ctx, MessageAckService_ProcessAck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageAckServiceServer is the server API for MessageAckService service.
// All implementations must embed UnimplementedMessageAckServiceServer
// for forward compatibility.
type MessageAckServiceServer interface {
	ProcessAck(context.Context, *ProcessAckRequest) (*ProcessAckResponse, error)
	mustEmbedUnimplementedMessageAckServiceServer()
}

// UnimplementedMessageAckServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageAckServiceServer struct{}

func (UnimplementedMessageAckServiceServer) ProcessAck(context.Context, *ProcessAckRequest) (*ProcessAckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessAck not implemented")
}
func (UnimplementedMessageAckServiceServer) mustEmbedUnimplementedMessageAckServiceServer() {}
func (UnimplementedMessageAckServiceServer) testEmbeddedByValue()                           {}

// UnsafeMessageAckServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageAckServiceServer will
// result in compilation errors.
type UnsafeMessageAckServiceServer interface {
	mustEmbedUnimplementedMessageAckServiceServer()
}

func RegisterMessageAckServiceServer(s grpc.ServiceRegistrar, srv MessageAckServiceServer) {
	// If the following call pancis, it indicates UnimplementedMessageAckServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageAckService_ServiceDesc, srv)
}

func _MessageAckService_ProcessAck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessAckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageAckServiceServer).ProcessAck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageAckService_ProcessAck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageAckServiceServer).ProcessAck(ctx, req.(*ProcessAckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageAckService_ServiceDesc is the grpc.ServiceDesc for MessageAckService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageAckService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "livechat.internal.MessageAckService",
	HandlerType: (*MessageAckServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessAck",
			Handler:    _MessageAckService_ProcessAck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal.proto",
}
