// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: internal.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeliverMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Message       *WsMessageDelivery     `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverMessageRequest) Reset() {
	*x = DeliverMessageRequest{}
	mi := &file_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverMessageRequest) ProtoMessage() {}

func (x *DeliverMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverMessageRequest.ProtoReflect.Descriptor instead.
func (*DeliverMessageRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{0}
}

func (x *DeliverMessageRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeliverMessageRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeliverMessageRequest) GetMessage() *WsMessageDelivery {
	if x != nil {
		return x.Message
	}
	return nil
}

type DeliverMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverMessageResponse) Reset() {
	*x = DeliverMessageResponse{}
	mi := &file_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverMessageResponse) ProtoMessage() {}

func (x *DeliverMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverMessageResponse.ProtoReflect.Descriptor instead.
func (*DeliverMessageResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{1}
}

type ProcessAckRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId       string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	AckType        string                 `protobuf:"bytes,3,opt,name=ack_type,json=ackType,proto3" json:"ack_type,omitempty"`
	EventSeq       uint64                 `protobuf:"varint,4,opt,name=event_seq,json=eventSeq,proto3" json:"event_seq,omitempty"`
	ConversationId string                 `protobuf:"bytes,5,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	LastReadSeq    uint64                 `protobuf:"varint,6,opt,name=last_read_seq,json=lastReadSeq,proto3" json:"last_read_seq,omitempty"`
	AckedAtMs      uint64                 `protobuf:"varint,7,opt,name=acked_at_ms,json=ackedAtMs,proto3" json:"acked_at_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessAckRequest) Reset() {
	*x = ProcessAckRequest{}
	mi := &file_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessAckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessAckRequest) ProtoMessage() {}

func (x *ProcessAckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessAckRequest.ProtoReflect.Descriptor instead.
func (*ProcessAckRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessAckRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ProcessAckRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ProcessAckRequest) GetAckType() string {
	if x != nil {
		return x.AckType
	}
	return ""
}

func (x *ProcessAckRequest) GetEventSeq() uint64 {
	if x != nil {
		return x.EventSeq
	}
	return 0
}

func (x *ProcessAckRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ProcessAckRequest) GetLastReadSeq() uint64 {
	if x != nil {
		return x.LastReadSeq
	}
	return 0
}

func (x *ProcessAckRequest) GetAckedAtMs() uint64 {
	if x != nil {
		return x.AckedAtMs
	}
	return 0
}

type ProcessAckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessAckResponse) Reset() {
	*x = ProcessAckResponse{}
	mi := &file_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessAckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessAckResponse) ProtoMessage() {}

func (x *ProcessAckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessAckResponse.ProtoReflect.Descriptor instead.
func (*ProcessAckResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessAckResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_internal_proto protoreflect.FileDescriptor

const file_internal_proto_rawDesc = "" +
	"\n" +
	"\x0einternal.proto\x12\x11livechat.internal\x1a\x0ews_frame.proto\"\x87\x01\n" +
	"\x15DeliverMessageRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x128\n" +
	"\amessage\x18\x03 \x01(\v2\x1e.livechat.ws.WsMessageDeliveryR\amessage\"\x18\n" +
	"\x16DeliverMessageResponse\"\xee\x01\n" +
	"\x11ProcessAckRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x19\n" +
	"\back_type\x18\x03 \x01(\tR\aackType\x12\x1b\n" +
	"\tevent_seq\x18\x04 \x01(\x04R\beventSeq\x12'\n" +
	"\x0fconversation_id\x18\x05 \x01(\tR\x0econversationId\x12\"\n" +
	"\rlast_read_seq\x18\x06 \x01(\x04R\vlastReadSeq\x12\x1e\n" +
	"\vacked_at_ms\x18\a \x01(\x04R\tackedAtMs\"0\n" +
	"\x12ProcessAckResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted2\x7f\n" +
	"\x16GatewayDeliveryService\x12e\n" +
	"\x0eDeliverMessage\x12(.livechat.internal.DeliverMessageRequest\x1a).livechat.internal.DeliverMessageResponse2n\n" +
	"\x11MessageAckService\x12Y\n" +
	"\n" +
	"ProcessAck\x12$.livechat.internal.ProcessAckRequest\x1a%.livechat.internal.ProcessAckResponseB=Z;github.com/tangzzz-fan/LiveChat/livechat-server/proto;protob\x06proto3"

var (
	file_internal_proto_rawDescOnce sync.Once
	file_internal_proto_rawDescData []byte
)

func file_internal_proto_rawDescGZIP() []byte {
	file_internal_proto_rawDescOnce.Do(func() {
		file_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_rawDesc), len(file_internal_proto_rawDesc)))
	})
	return file_internal_proto_rawDescData
}

var file_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_proto_goTypes = []any{
	(*DeliverMessageRequest)(nil),  // 0: livechat.internal.DeliverMessageRequest
	(*DeliverMessageResponse)(nil), // 1: livechat.internal.DeliverMessageResponse
	(*ProcessAckRequest)(nil),      // 2: livechat.internal.ProcessAckRequest
	(*ProcessAckResponse)(nil),     // 3: livechat.internal.ProcessAckResponse
	(*WsMessageDelivery)(nil),      // 4: livechat.ws.WsMessageDelivery
}
var file_internal_proto_depIdxs = []int32{
	4, // 0: livechat.internal.DeliverMessageRequest.message:type_name -> livechat.ws.WsMessageDelivery
	0, // 1: livechat.internal.GatewayDeliveryService.DeliverMessage:input_type -> livechat.internal.DeliverMessageRequest
	2, // 2: livechat.internal.MessageAckService.ProcessAck:input_type -> livechat.internal.ProcessAckRequest
	1, // 3: livechat.internal.GatewayDeliveryService.DeliverMessage:output_type -> livechat.internal.DeliverMessageResponse
	3, // 4: livechat.internal.MessageAckService.ProcessAck:output_type -> livechat.internal.ProcessAckResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_init() }
func file_internal_proto_init() {
	if File_internal_proto != nil {
		return
	}
	file_ws_frame_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_rawDesc), len(file_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_internal_proto_goTypes,
		DependencyIndexes: file_internal_proto_depIdxs,
		MessageInfos:      file_internal_proto_msgTypes,
	}.Build()
	File_internal_proto = out.File
	file_internal_proto_goTypes = nil
	file_internal_proto_depIdxs = nil
}
