// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: ws_frame.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WsFrame is the outer envelope for all WebSocket messages.
type WsFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`                     // protocol version (currently 0x01)
	Opcode        uint32                 `protobuf:"varint,2,opt,name=opcode,proto3" json:"opcode,omitempty"`                       // operation code
	SeqId         uint64                 `protobuf:"varint,3,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`            // frame sequence number (client increments)
	AckSeqId      uint64                 `protobuf:"varint,4,opt,name=ack_seq_id,json=ackSeqId,proto3" json:"ack_seq_id,omitempty"` // piggyback ACK: last received seq_id
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`                      // opcode-specific protobuf payload
	TimestampMs   int64                  `protobuf:"varint,6,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	TraceId       string                 `protobuf:"bytes,7,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WsFrame) Reset() {
	*x = WsFrame{}
	mi := &file_ws_frame_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WsFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsFrame) ProtoMessage() {}

func (x *WsFrame) ProtoReflect() protoreflect.Message {
	mi := &file_ws_frame_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsFrame.ProtoReflect.Descriptor instead.
func (*WsFrame) Descriptor() ([]byte, []int) {
	return file_ws_frame_proto_rawDescGZIP(), []int{0}
}

func (x *WsFrame) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *WsFrame) GetOpcode() uint32 {
	if x != nil {
		return x.Opcode
	}
	return 0
}

func (x *WsFrame) GetSeqId() uint64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *WsFrame) GetAckSeqId() uint64 {
	if x != nil {
		return x.AckSeqId
	}
	return 0
}

func (x *WsFrame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WsFrame) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *WsFrame) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	AppVersion    string                 `protobuf:"bytes,4,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	ProtocolVer   uint32                 `protobuf:"varint,5,opt,name=protocol_ver,json=protocolVer,proto3" json:"protocol_ver,omitempty"`
	LastEventSeq  uint64                 `protobuf:"varint,6,opt,name=last_event_seq,json=lastEventSeq,proto3" json:"last_event_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_ws_frame_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ws_frame_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_ws_frame_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *HandshakeRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *HandshakeRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *HandshakeRequest) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *HandshakeRequest) GetProtocolVer() uint32 {
	if x != nil {
		return x.ProtocolVer
	}
	return 0
}

func (x *HandshakeRequest) GetLastEventSeq() uint64 {
	if x != nil {
		return x.LastEventSeq
	}
	return 0
}

type HandshakeResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Success            bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SessionId          string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	NegotiatedVer      uint32                 `protobuf:"varint,3,opt,name=negotiated_ver,json=negotiatedVer,proto3" json:"negotiated_ver,omitempty"`
	ServerTimeMs       uint64                 `protobuf:"varint,4,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"`
	ErrorMessage       string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	HeartbeatIntervalS uint32                 `protobuf:"varint,6,opt,name=heartbeat_interval_s,json=heartbeatIntervalS,proto3" json:"heartbeat_interval_s,omitempty"`
	LatestEventSeq     uint64                 `protobuf:"varint,7,opt,name=latest_event_seq,json=latestEventSeq,proto3" json:"latest_event_seq,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_ws_frame_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ws_frame_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_ws_frame_proto_rawDescGZIP(), []int{2}
}

func (x *HandshakeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HandshakeResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HandshakeResponse) GetNegotiatedVer() uint32 {
	if x != nil {
		return x.NegotiatedVer
	}
	return 0
}

func (x *HandshakeResponse) GetServerTimeMs() uint64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

func (x *HandshakeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *HandshakeResponse) GetHeartbeatIntervalS() uint32 {
	if x != nil {
		return x.HeartbeatIntervalS
	}
	return 0
}

func (x *HandshakeResponse) GetLatestEventSeq() uint64 {
	if x != nil {
		return x.LatestEventSeq
	}
	return 0
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_ws_frame_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_ws_frame_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_ws_frame_proto_rawDescGZIP(), []int{3}
}

type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTimeMs  uint64                 `protobuf:"varint,1,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_ws_frame_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_ws_frame_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_ws_frame_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatAck) GetServerTimeMs() uint64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

type MessageAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventSeq       uint64                 `protobuf:"varint,1,opt,name=event_seq,json=eventSeq,proto3" json:"event_seq,omitempty"`
	AckType        string                 `protobuf:"bytes,2,opt,name=ack_type,json=ackType,proto3" json:"ack_type,omitempty"`
	AckedAtMs      uint64                 `protobuf:"varint,3,opt,name=acked_at_ms,json=ackedAtMs,proto3" json:"acked_at_ms,omitempty"`
	ConversationId string                 `protobuf:"bytes,4,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	LastReadSeq    uint64                 `protobuf:"varint,5,opt,name=last_read_seq,json=lastReadSeq,proto3" json:"last_read_seq,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageAck) Reset() {
	*x = MessageAck{}
	mi := &file_ws_frame_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageAck) ProtoMessage() {}

func (x *MessageAck) ProtoReflect() protoreflect.Message {
	mi := &file_ws_frame_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageAck.ProtoReflect.Descriptor instead.
func (*MessageAck) Descriptor() ([]byte, []int) {
	return file_ws_frame_proto_rawDescGZIP(), []int{5}
}

func (x *MessageAck) GetEventSeq() uint64 {
	if x != nil {
		return x.EventSeq
	}
	return 0
}

func (x *MessageAck) GetAckType() string {
	if x != nil {
		return x.AckType
	}
	return ""
}

func (x *MessageAck) GetAckedAtMs() uint64 {
	if x != nil {
		return x.AckedAtMs
	}
	return 0
}

func (x *MessageAck) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessageAck) GetLastReadSeq() uint64 {
	if x != nil {
		return x.LastReadSeq
	}
	return 0
}

type ErrorFrame struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode       uint32                 `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ShouldReconnect bool                   `protobuf:"varint,3,opt,name=should_reconnect,json=shouldReconnect,proto3" json:"should_reconnect,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ErrorFrame) Reset() {
	*x = ErrorFrame{}
	mi := &file_ws_frame_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorFrame) ProtoMessage() {}

func (x *ErrorFrame) ProtoReflect() protoreflect.Message {
	mi := &file_ws_frame_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorFrame.ProtoReflect.Descriptor instead.
func (*ErrorFrame) Descriptor() ([]byte, []int) {
	return file_ws_frame_proto_rawDescGZIP(), []int{6}
}

func (x *ErrorFrame) GetErrorCode() uint32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ErrorFrame) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorFrame) GetShouldReconnect() bool {
	if x != nil {
		return x.ShouldReconnect
	}
	return false
}

type WsMessageDelivery struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ServerMessageId    string                 `protobuf:"bytes,1,opt,name=server_message_id,json=serverMessageId,proto3" json:"server_message_id,omitempty"`
	ConversationId     string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ConversationSeq    uint64                 `protobuf:"varint,3,opt,name=conversation_seq,json=conversationSeq,proto3" json:"conversation_seq,omitempty"`
	SenderUserId       uint64                 `protobuf:"varint,4,opt,name=sender_user_id,json=senderUserId,proto3" json:"sender_user_id,omitempty"`
	SenderDeviceId     string                 `protobuf:"bytes,5,opt,name=sender_device_id,json=senderDeviceId,proto3" json:"sender_device_id,omitempty"`
	MessageType        string                 `protobuf:"bytes,6,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	Content            string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"` // JSON-encoded
	ServerReceivedAtMs int64                  `protobuf:"varint,8,opt,name=server_received_at_ms,json=serverReceivedAtMs,proto3" json:"server_received_at_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WsMessageDelivery) Reset() {
	*x = WsMessageDelivery{}
	mi := &file_ws_frame_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WsMessageDelivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsMessageDelivery) ProtoMessage() {}

func (x *WsMessageDelivery) ProtoReflect() protoreflect.Message {
	mi := &file_ws_frame_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsMessageDelivery.ProtoReflect.Descriptor instead.
func (*WsMessageDelivery) Descriptor() ([]byte, []int) {
	return file_ws_frame_proto_rawDescGZIP(), []int{7}
}

func (x *WsMessageDelivery) GetServerMessageId() string {
	if x != nil {
		return x.ServerMessageId
	}
	return ""
}

func (x *WsMessageDelivery) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *WsMessageDelivery) GetConversationSeq() uint64 {
	if x != nil {
		return x.ConversationSeq
	}
	return 0
}

func (x *WsMessageDelivery) GetSenderUserId() uint64 {
	if x != nil {
		return x.SenderUserId
	}
	return 0
}

func (x *WsMessageDelivery) GetSenderDeviceId() string {
	if x != nil {
		return x.SenderDeviceId
	}
	return ""
}

func (x *WsMessageDelivery) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *WsMessageDelivery) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *WsMessageDelivery) GetServerReceivedAtMs() int64 {
	if x != nil {
		return x.ServerReceivedAtMs
	}
	return 0
}

type SyncEventMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventSeq       uint64                 `protobuf:"varint,1,opt,name=event_seq,json=eventSeq,proto3" json:"event_seq,omitempty"`
	EventType      string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	UserId         uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,4,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Payload        string                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"` // JSON-encoded
	CreatedAtMs    int64                  `protobuf:"varint,6,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncEventMessage) Reset() {
	*x = SyncEventMessage{}
	mi := &file_ws_frame_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncEventMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncEventMessage) ProtoMessage() {}

func (x *SyncEventMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ws_frame_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncEventMessage.ProtoReflect.Descriptor instead.
func (*SyncEventMessage) Descriptor() ([]byte, []int) {
	return file_ws_frame_proto_rawDescGZIP(), []int{8}
}

func (x *SyncEventMessage) GetEventSeq() uint64 {
	if x != nil {
		return x.EventSeq
	}
	return 0
}

func (x *SyncEventMessage) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *SyncEventMessage) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SyncEventMessage) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *SyncEventMessage) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *SyncEventMessage) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

type ConversationUpdate struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ConversationId     string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	LastMessagePreview string                 `protobuf:"bytes,2,opt,name=last_message_preview,json=lastMessagePreview,proto3" json:"last_message_preview,omitempty"`
	LastMessageAtMs    int64                  `protobuf:"varint,3,opt,name=last_message_at_ms,json=lastMessageAtMs,proto3" json:"last_message_at_ms,omitempty"`
	UnreadCount        int32                  `protobuf:"varint,4,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConversationUpdate) Reset() {
	*x = ConversationUpdate{}
	mi := &file_ws_frame_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationUpdate) ProtoMessage() {}

func (x *ConversationUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_ws_frame_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationUpdate.ProtoReflect.Descriptor instead.
func (*ConversationUpdate) Descriptor() ([]byte, []int) {
	return file_ws_frame_proto_rawDescGZIP(), []int{9}
}

func (x *ConversationUpdate) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationUpdate) GetLastMessagePreview() string {
	if x != nil {
		return x.LastMessagePreview
	}
	return ""
}

func (x *ConversationUpdate) GetLastMessageAtMs() int64 {
	if x != nil {
		return x.LastMessageAtMs
	}
	return 0
}

func (x *ConversationUpdate) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

var File_ws_frame_proto protoreflect.FileDescriptor

const file_ws_frame_proto_rawDesc = "" +
	"\n" +
	"\x0ews_frame.proto\x12\vlivechat.ws\"\xc8\x01\n" +
	"\aWsFrame\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x16\n" +
	"\x06opcode\x18\x02 \x01(\rR\x06opcode\x12\x15\n" +
	"\x06seq_id\x18\x03 \x01(\x04R\x05seqId\x12\x1c\n" +
	"\n" +
	"ack_seq_id\x18\x04 \x01(\x04R\backSeqId\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12!\n" +
	"\ftimestamp_ms\x18\x06 \x01(\x03R\vtimestampMs\x12\x19\n" +
	"\btrace_id\x18\a \x01(\tR\atraceId\"\xd8\x01\n" +
	"\x10HandshakeRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x1f\n" +
	"\vapp_version\x18\x04 \x01(\tR\n" +
	"appVersion\x12!\n" +
	"\fprotocol_ver\x18\x05 \x01(\rR\vprotocolVer\x12$\n" +
	"\x0elast_event_seq\x18\x06 \x01(\x04R\flastEventSeq\"\x9a\x02\n" +
	"\x11HandshakeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12%\n" +
	"\x0enegotiated_ver\x18\x03 \x01(\rR\rnegotiatedVer\x12$\n" +
	"\x0eserver_time_ms\x18\x04 \x01(\x04R\fserverTimeMs\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x120\n" +
	"\x14heartbeat_interval_s\x18\x06 \x01(\rR\x12heartbeatIntervalS\x12(\n" +
	"\x10latest_event_seq\x18\a \x01(\x04R\x0elatestEventSeq\"\v\n" +
	"\tHeartbeat\"4\n" +
	"\fHeartbeatAck\x12$\n" +
	"\x0eserver_time_ms\x18\x01 \x01(\x04R\fserverTimeMs\"\xb1\x01\n" +
	"\n" +
	"MessageAck\x12\x1b\n" +
	"\tevent_seq\x18\x01 \x01(\x04R\beventSeq\x12\x19\n" +
	"\back_type\x18\x02 \x01(\tR\aackType\x12\x1e\n" +
	"\vacked_at_ms\x18\x03 \x01(\x04R\tackedAtMs\x12'\n" +
	"\x0fconversation_id\x18\x04 \x01(\tR\x0econversationId\x12\"\n" +
	"\rlast_read_seq\x18\x05 \x01(\x04R\vlastReadSeq\"p\n" +
	"\n" +
	"ErrorFrame\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\rR\terrorCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x10should_reconnect\x18\x03 \x01(\bR\x0fshouldReconnect\"\xd3\x02\n" +
	"\x11WsMessageDelivery\x12*\n" +
	"\x11server_message_id\x18\x01 \x01(\tR\x0fserverMessageId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12)\n" +
	"\x10conversation_seq\x18\x03 \x01(\x04R\x0fconversationSeq\x12$\n" +
	"\x0esender_user_id\x18\x04 \x01(\x04R\fsenderUserId\x12(\n" +
	"\x10sender_device_id\x18\x05 \x01(\tR\x0esenderDeviceId\x12!\n" +
	"\fmessage_type\x18\x06 \x01(\tR\vmessageType\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x121\n" +
	"\x15server_received_at_ms\x18\b \x01(\x03R\x12serverReceivedAtMs\"\xce\x01\n" +
	"\x10SyncEventMessage\x12\x1b\n" +
	"\tevent_seq\x18\x01 \x01(\x04R\beventSeq\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x04 \x01(\tR\x0econversationId\x12\x18\n" +
	"\apayload\x18\x05 \x01(\tR\apayload\x12\"\n" +
	"\rcreated_at_ms\x18\x06 \x01(\x03R\vcreatedAtMs\"\xbf\x01\n" +
	"\x12ConversationUpdate\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x120\n" +
	"\x14last_message_preview\x18\x02 \x01(\tR\x12lastMessagePreview\x12+\n" +
	"\x12last_message_at_ms\x18\x03 \x01(\x03R\x0flastMessageAtMs\x12!\n" +
	"\funread_count\x18\x04 \x01(\x05R\vunreadCountB=Z;github.com/tangzzz-fan/LiveChat/livechat-server/proto;protob\x06proto3"

var (
	file_ws_frame_proto_rawDescOnce sync.Once
	file_ws_frame_proto_rawDescData []byte
)

func file_ws_frame_proto_rawDescGZIP() []byte {
	file_ws_frame_proto_rawDescOnce.Do(func() {
		file_ws_frame_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ws_frame_proto_rawDesc), len(file_ws_frame_proto_rawDesc)))
	})
	return file_ws_frame_proto_rawDescData
}

var file_ws_frame_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_ws_frame_proto_goTypes = []any{
	(*WsFrame)(nil),            // 0: livechat.ws.WsFrame
	(*HandshakeRequest)(nil),   // 1: livechat.ws.HandshakeRequest
	(*HandshakeResponse)(nil),  // 2: livechat.ws.HandshakeResponse
	(*Heartbeat)(nil),          // 3: livechat.ws.Heartbeat
	(*HeartbeatAck)(nil),       // 4: livechat.ws.HeartbeatAck
	(*MessageAck)(nil),         // 5: livechat.ws.MessageAck
	(*ErrorFrame)(nil),         // 6: livechat.ws.ErrorFrame
	(*WsMessageDelivery)(nil),  // 7: livechat.ws.WsMessageDelivery
	(*SyncEventMessage)(nil),   // 8: livechat.ws.SyncEventMessage
	(*ConversationUpdate)(nil), // 9: livechat.ws.ConversationUpdate
}
var file_ws_frame_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ws_frame_proto_init() }
func file_ws_frame_proto_init() {
	if File_ws_frame_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ws_frame_proto_rawDesc), len(file_ws_frame_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ws_frame_proto_goTypes,
		DependencyIndexes: file_ws_frame_proto_depIdxs,
		MessageInfos:      file_ws_frame_proto_msgTypes,
	}.Build()
	File_ws_frame_proto = out.File
	file_ws_frame_proto_goTypes = nil
	file_ws_frame_proto_depIdxs = nil
}
